version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: $IMAGE_NAME
    container_name: prime-edu-fe-develop
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"